use crate::domain::errors::ApiError;
use std::path::Path;
use tokio::process::Command;

/// Ensure ~/.claude/ is a git repo (init if not).
pub async fn ensure_git_repo(claude_home: &Path) -> Result<(), ApiError> {
    let git_dir = claude_home.join(".git");
    if tokio::fs::try_exists(&git_dir).await.unwrap_or(false) {
        return Ok(());
    }

    // Write .gitignore to exclude noisy files
    let gitignore_path = claude_home.join(".gitignore");
    if !tokio::fs::try_exists(&gitignore_path)
        .await
        .unwrap_or(false)
    {
        tokio::fs::write(
            &gitignore_path,
            "# Auto-generated by ClaudeAdmin Timeline\n\
             *.tmp\n\
             audit.log\n\
             statsig/\n\
             .credentials*\n\
             todo-*.md\n",
        )
        .await?;
    }

    let output = Command::new("git")
        .args(["init"])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("Failed to run git init: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(ApiError::Internal(format!("git init failed: {}", stderr)));
    }

    // Initial commit
    commit_all(claude_home, "Initial timeline snapshot").await?;

    tracing::info!("Git timeline initialized in {}", claude_home.display());
    Ok(())
}

/// Stage all changes and create a commit with the given message.
pub async fn commit_all(claude_home: &Path, message: &str) -> Result<(), ApiError> {
    // git add -A
    let output = Command::new("git")
        .args(["add", "-A"])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git add failed: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        tracing::warn!("git add warning: {}", stderr);
    }

    // Check if there's anything to commit
    let status = Command::new("git")
        .args(["status", "--porcelain"])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git status failed: {}", e)))?;

    if status.stdout.is_empty() {
        return Ok(()); // Nothing to commit
    }

    // git commit
    let output = Command::new("git")
        .args([
            "-c",
            "user.name=ClaudeAdmin",
            "-c",
            "user.email=timeline@claude-admin.local",
            "commit",
            "-m",
            message,
        ])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git commit failed: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        // "nothing to commit" is not an error
        if !stderr.contains("nothing to commit") {
            tracing::warn!("git commit warning: {}", stderr);
        }
    }

    Ok(())
}

/// Timeline entry representing a git commit.
#[derive(serde::Serialize)]
pub struct TimelineEntry {
    pub hash: String,
    pub message: String,
    pub timestamp: String,
    pub files_changed: u32,
}

/// List recent timeline commits.
pub async fn list_timeline(
    claude_home: &Path,
    limit: usize,
) -> Result<Vec<TimelineEntry>, ApiError> {
    let git_dir = claude_home.join(".git");
    if !tokio::fs::try_exists(&git_dir).await.unwrap_or(false) {
        return Ok(vec![]);
    }

    let output = Command::new("git")
        .args([
            "log",
            &format!("-{}", limit),
            "--pretty=format:%H|%s|%aI",
            "--shortstat",
        ])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git log failed: {}", e)))?;

    let stdout = String::from_utf8_lossy(&output.stdout);
    let mut entries = Vec::new();
    let mut lines = stdout.lines().peekable();

    while let Some(line) = lines.next() {
        if line.is_empty() {
            continue;
        }

        // Parse commit line: hash|message|timestamp
        let parts: Vec<&str> = line.splitn(3, '|').collect();
        if parts.len() < 3 {
            continue;
        }

        let hash = parts[0].to_string();
        let message = parts[1].to_string();
        let timestamp = parts[2].to_string();

        // Next non-empty line might be the stat line
        let mut files_changed = 0u32;
        while let Some(next) = lines.peek() {
            if next.is_empty() {
                lines.next();
                continue;
            }
            if next.contains("file") && next.contains("changed") {
                // Parse "1 file changed, 2 insertions(+)"
                if let Some(n) = next.split_whitespace().next() {
                    files_changed = n.parse().unwrap_or(0);
                }
                lines.next();
            }
            break;
        }

        entries.push(TimelineEntry {
            hash,
            message,
            timestamp,
            files_changed,
        });
    }

    Ok(entries)
}

/// Get the diff for a specific commit.
pub async fn get_commit_diff(claude_home: &Path, commit_hash: &str) -> Result<String, ApiError> {
    // Validate hash (only hex chars)
    if !commit_hash.chars().all(|c| c.is_ascii_hexdigit()) || commit_hash.len() < 7 {
        return Err(ApiError::BadRequest("Invalid commit hash".to_string()));
    }

    let output = Command::new("git")
        .args(["show", "--stat", "--patch", commit_hash])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git show failed: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(ApiError::NotFound(format!("Commit not found: {}", stderr)));
    }

    Ok(String::from_utf8_lossy(&output.stdout).to_string())
}

/// Restore ~/.claude/ to a specific commit state.
/// Creates a new commit "Restore to <hash>" so you can always go forward again.
pub async fn restore_to_commit(claude_home: &Path, commit_hash: &str) -> Result<(), ApiError> {
    // Validate hash
    if !commit_hash.chars().all(|c| c.is_ascii_hexdigit()) || commit_hash.len() < 7 {
        return Err(ApiError::BadRequest("Invalid commit hash".to_string()));
    }

    // First commit current state so we don't lose anything
    commit_all(claude_home, "Auto-save before restore").await?;

    // git checkout <hash> -- .  (restore files without moving HEAD)
    let output = Command::new("git")
        .args(["checkout", commit_hash, "--", "."])
        .current_dir(claude_home)
        .output()
        .await
        .map_err(|e| ApiError::Internal(format!("git checkout failed: {}", e)))?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(ApiError::Internal(format!("Restore failed: {}", stderr)));
    }

    // Commit the restored state
    let short_hash = &commit_hash[..7.min(commit_hash.len())];
    commit_all(claude_home, &format!("Restore to {}", short_hash)).await?;

    Ok(())
}
